version: '3'
services:
  server:
    build:
      context: ./Container1
      dockerfile: Dockerfile
    container_name: server
    networks:
      - local
  client:
    build:
      context: ./Container2
      dockerfile: Dockerfile
    container_name: client
    ports:
        - "10022:22"
    networks:
      - local
networks:
    local:
        driver: bridge
